Portfolio: add a contact form and finish the mobile version
LoviMadaan/My-Portfolio pull request #10
Opened 2023-01-25 07:16 UTC by LoviMadaan

### In this branch 
- I have added contact-me form.
- I have added form submission action.
- I have updated html and css.

2023-01-25 09:23 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @LoviMadaan 👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔️ Professional PR. 👍
✔️ Professional Readme. 👍

## Required Changes ♻️

- [ ] **Check the comments below 👇**

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 09:23 UTC, TuyishimireEric commented on style.css
> +}
- [x] **Good job so far ✌✌** However, it would be better to adjust the padding and margin of this content to replicate the Figma design, you may kindly follow this [link](https://rawcdn.githack.com/LoviMadaan/My-Portfolio/058127385143b1a7591fbf81a2aa9fb91f29aca6/index.html) for more info 👍 👍 

![image](https://user-images.githubusercontent.com/102757126/214525723-72a0ede9-973b-4858-8943-4cefc543464e.png)

2023-01-25 09:23 UTC, TuyishimireEric commented on style.css
> +}
- [x] I think it would be better to remove ```margin-left: 15%``` for this title, as it is aligned in the center on the original design, It would be better to add ```align-items: center;``` in the container to align your elements in the center except for the button 👍 :

2023-01-25 09:23 UTC, TuyishimireEric commented on style.css
> +}
- [ ] **Good job on adding the hover to your button 👍** However the button interactions such as hover, active (when it's pressed), disabled, and enable (default state) should be styled as shown in the Figma template. 😎😎

You may try to check the following button styles for your Reference
![image](https://user-images.githubusercontent.com/102757126/214524063-51156de3-bb8d-4104-87ff-3e3a5d0b19f0.png)

2023-01-27 14:53 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @LoviMadaan 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

## Optional:

- [ ] @ybadr99 Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 

_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 14:53 UTC, ha-manel commented on style.css
> +  left: auto; */
[Optional]

- [ ] Please consider removing commented pieces of code to avoid having messy code 👍

2023-01-27 14:53 UTC, ha-manel commented on style.css
> +  margin-left: 15%;
- [ ] Kindly use flexbox on the container (flex-direction would be column) and `align-items: center` to center all the elements inside the container instead of adding margins to center elements as suggested by the previous reviewer because it may be centered for a certain screen size but it won't be for other sizes, however, flexbox calculates the center no matter what the screen size is 👍

2023-01-27 14:53 UTC, ha-manel commented on style.css
> +  padding: 20px;
- [ ] Kindly reduce the padding of the container to match the design better as requested by the previous reviewer 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/215115865-4b2dd042-04d0-4b91-b14d-b922c50bcfc1.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/215115487-d730707a-e9b3-4a11-98e4-6506b266a9ea.png)

2023-01-27 14:53 UTC, ha-manel commented on style.css
> +  width: 375px;
[Optional]

- [ ] Please consider removing this width property from the container because it's making the content overflow which adds a white space on the right of the page (when I removed this width property it was gone and the container looked better 👍 )

![image](https://user-images.githubusercontent.com/50721479/215115805-1b718909-3ea5-48e3-969f-16c8430abdba.png)

2023-01-28 11:03 UTC, Tadesse-Alemayehu approved these changes
### Hi @LoviMadaan 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![cx](https://user-images.githubusercontent.com/69077061/215262988-ae7485db-51ee-4b06-a7b2-9348ebf47c19.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewers. ✅
 - [ ]  Correct GitHub Flow. ✅
 - [ ]  Good commit history. ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 11:03 UTC, Tadesse-Alemayehu commented on style.css
>    justify-content: center;
- [Optional] Dear @LoviMadaan, Good job already, To improve your design your code reduces the bottom margin to zero as it is stoping your design from reaching the bottom.
![Screenshot 2023-01-28 135850](https://user-images.githubusercontent.com/69077061/215263088-9779e869-9caf-448f-a579-4b3864ecad9b.png)

2023-01-28 11:21 UTC, merged